# Generated by Django 6.0.2 on 2026-02-27 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_free',
        ),
    ]
